<<<<<<< HEAD
# This workflow will do a clean installation of node dependencies, cache/restore them, and build the source code
=======
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
>>>>>>> 8a1990c (Create node.js.yml)

name: Node.js CI

on:
  push:
<<<<<<< HEAD
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [21.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: yarn install
      - run: yarn build
      - run: node sitemap.js
=======
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  delete_files:
    runs-on: ubuntu-20.04
    name: Delete build directory
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
    env:
      prepo: ${{github.repository}}
    steps:
      - uses: actions/checkout@v2
      - name: Removing unnecessary files
        run: |
          rm -r build
          ls -la
      - name: Pushing to develop branch
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: develop
          message: Deleted build directory
          force: true
          
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [21.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: yarn install
    - run: yarn build
    - run: node sitemap.js
    #- run: yarn postbuild
>>>>>>> 8a1990c (Create node.js.yml)
