name: Node.js CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [21.x]  # Adjust the Node.js version as needed
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Check and Delete Dist Folder
        run: |
          if [ -d "dist" ]; then
            echo "Deleting existing `dist` folder."
            rm -rf dist
          fi
      - name: Create Dist Folder
        run: |
          mkdir -p dist
      - name: Install Dependencies
        run: |
          yarn install
      - name: Build
        run: |
          yarn build
      - name: Run sitemap.js
        run: |
          node sitemap.js
      - name: Debugging Information
        run: |
          echo "Listing files in the current directory:"
          ls -R
          echo "Current directory: $PWD"
      - name: Archive Dist Folder
        run: |
          zip -r dist.zip dist
      - name: Upload Dist Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Download and Extract Dist Archive
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Commit and Push Dist Files
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add dist
          git commit -m "Update and deploy 'dist' files with GitHub Actions workflow"
          git push origin HEAD:develop
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
