name: Node.js CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [21.x]  # Adjust the Node.js version as needed
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Check and Delete Build Folder
        run: |
          if [ -d "build" ]; then
            echo "Deleting existing build folder."
            rm -rf build
          fi

      - name: Create Build Folder
        run: |
          mkdir -p build

      - name: Install Dependencies
        run: |
          yarn install

      - name: Build
        run: |
          yarn build

      - name: Debugging Information
        run: |
          echo "Listing files in the current directory:"
          ls -R
          echo "Current directory: $PWD"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: .

      - name: Run sitemap.js
        run: |
          node sitemap.js
